spring:
  rabbitmq:
    host: 47.244.18.29
    port: 5672
    username: ocean
    password: huhaiyang
    virtual-host: /test
    connection-timeout: 2000ms
    publisher-confirms: true  #confirmListener
    publisher-returns: true   #returnListener
    template:
      mandatory: true

